project:
  type: website
  output-dir: docs

website:
  title: "Allison Horst"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: talks_workshops.qmd
        text: Talks / Workshops
      - href: cv.qmd
        text: CV
      - href: projects.qmd
        text: Projects
      - href: posts.qmd
        text: Blog
    right:
      - icon: github
        href: https://github.com/allisonhorst/
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/allison_horst

format:
  html:
    theme: styles.scss
    mainfont: 'Bellota Text'
    toc: true



